name: inflow_stellar_mobile
description: "inFlow — Real-time salary streaming on Stellar (Mobile App)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_secure_storage: ^9.2.0
  google_fonts: ^8.0.2
  http: ^1.6.0
  local_auth: ^2.3.0
  pinput: ^6.0.2
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
