blank_issues_enabled: false
contact_links:
  - name: Security Vulnerabilities
    url: https://github.com/InflowFinance/inflow-stellar/security/advisories/new
    about: Please report security vulnerabilities confidentially here.
