name = "inflow-relay"
main = "src/index.ts"
compatibility_date = "2024-09-01"
account_id = "ca311252b49c8488885f505793a347b3"

[vars]
STELLAR_NETWORK = "testnet"
INFLOW_CONTRACT_ID = "CCCFBMNEBOV7KTVWLEBR2FFUGQC4KSL5TSITVU5ZPQ2U3PNLQJGX62W2"

[[kv_namespaces]]
binding = "KEYPAIRS"
id = "74e139fbf071487fb7a0704d320c9035"

[[kv_namespaces]]
binding = "STREAM_LINKS"
id = "d4b66e35d15a4f2ab2785ca5978db04d"

